CREATE TABLE IF NOT EXISTS users (
    email VARCHAR(64) PRIMARY KEY,
    password VARCHAR(64) NOT NULL,
    firstname VARCHAR(64) NOT NULL,
    lastname VARCHAR(64) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    city VARCHAR(64) NOT NULL,
    country VARCHAR(32) NOT NULL
    
);

CREATE TABLE IF NOT EXISTS session (
    email VARCHAR(64) PRIMARY KEY,
    token VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
    SENT_BY VARCHAR(64) NOT NULL,
    SENT_TO VARCHAR(64) NOT NULL,
    POST TEXT NOT NULL,
    POST_ID INTEGER PRIMARY KEY AUTOINCREMENT
);
